version: "3.8"
services:
  ts:
    image: typesense/typesense:0.23.1
    ports:
      - "8109:8108"
    volumes:
      - "ts_data:/data"
    environment:
      TYPESENSE_API_KEY: "LgpWxVQUPctPHW9VScyTjPae8s94UB82"
      TYPESENSE_DATA_DIR: "/data"

volumes:
  ts_data:
